pipeline {
    agent { docker { image 'maven:3.3.3' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn -f config-server/pom.xml -B -DskipTests clean package'
            }
        }
    }
}