pipeline {
    agent { docker { image 'maven:3.3.3' } }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -f config-server/pom.xml -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f config-server/pom.xml test'
            }
            post {
                always {
                    junit 'config-server/target/surefire-reports/*.xml'
                }
            }
        }
    }
}